// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpm40jEp4nngIZQl85CDmaxuWZj5WRCNc',
    appId: '1:16329399063:web:0b19606cd9920a53247552',
    messagingSenderId: '16329399063',
    projectId: 'healthcare-app-ba3ba',
    authDomain: 'healthcare-app-ba3ba.firebaseapp.com',
    storageBucket: 'healthcare-app-ba3ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeCODIfYSTBBW5igkJfscPEOY_m_6561k',
    appId: '1:16329399063:android:9b9af8551d2c3360247552',
    messagingSenderId: '16329399063',
    projectId: 'healthcare-app-ba3ba',
    storageBucket: 'healthcare-app-ba3ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtvhvZwf6K4fy7GCzB6twPTt6JYKuwaTQ',
    appId: '1:16329399063:ios:8c126a086fb86b59247552',
    messagingSenderId: '16329399063',
    projectId: 'healthcare-app-ba3ba',
    storageBucket: 'healthcare-app-ba3ba.appspot.com',
    iosClientId: '16329399063-q0fp43m04suiojf8qcnkmr5h6psvt64g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtvhvZwf6K4fy7GCzB6twPTt6JYKuwaTQ',
    appId: '1:16329399063:ios:8c126a086fb86b59247552',
    messagingSenderId: '16329399063',
    projectId: 'healthcare-app-ba3ba',
    storageBucket: 'healthcare-app-ba3ba.appspot.com',
    iosClientId: '16329399063-q0fp43m04suiojf8qcnkmr5h6psvt64g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
